name: Build Plugins

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone Artemis
        uses: actions/checkout@v2
        with:
          repository: Artemis-RGB/Artemis
          path: Artemis

      - name: Build Artemis
        run: dotnet build .\Artemis\src\Artemis.sln

      - name: Clone Plugins
        uses: actions/checkout@v2
        with:
          path: Plugins

      - name: Build Plugins
        run: dotnet publish -c Release .\Plugins\WinLockState.sln

      - name: Upload WinLockState
        uses: actions/upload-artifact@v2
        with:
          name: WinLockState
          path: .\Plugins\WinLockState\bin\x64\Release\net6.0\publish
